# Generated by Django 3.1.7 on 2021-04-22 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('AuthorID', models.IntegerField(db_column='AuthorID', primary_key=True, serialize=False, verbose_name='AuthorID')),
                ('FirstName', models.CharField(max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255)),
                ('DateAdded', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookID', models.IntegerField(db_column='BookID', primary_key=True, serialize=False, verbose_name='BookID')),
                ('Title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('CopyrightYear', models.CharField(max_length=255, null=True, verbose_name='CopyrightYear')),
                ('DateAdded', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='DateAdded')),
                ('ISBN', models.CharField(max_length=255, null=True, verbose_name='ISBN')),
                ('AuthorID', models.ForeignKey(db_column='AuthorID', on_delete=django.db.models.deletion.CASCADE, to='home.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('ConditionID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ConditionID')),
                ('Condition', models.CharField(max_length=255, null=True, verbose_name='Condition')),
            ],
        ),
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('CoverID', models.IntegerField(primary_key=True, serialize=False, verbose_name='CoverID')),
                ('Cover', models.CharField(max_length=255, null=True, verbose_name='Cover')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('City', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('Zip', models.CharField(max_length=5, null=True)),
                ('HomePhone', models.CharField(max_length=11, null=True)),
                ('DateAdded', models.DateField(default=django.utils.timezone.now, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False, verbose_name='PublisherID')),
                ('Publisher', models.CharField(max_length=255, null=True, verbose_name='Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('SeriesID', models.IntegerField(primary_key=True, serialize=False, verbose_name='SeriesID')),
                ('Series', models.CharField(max_length=255, null=True, verbose_name='Series')),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='DateAdded')),
            ],
        ),
        migrations.CreateModel(
            name='SmallShelfSigns',
            fields=[
                ('SignID', models.IntegerField(primary_key=True, serialize=False, verbose_name='SignID')),
                ('Description', models.CharField(max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('TopicID', models.IntegerField(primary_key=True, serialize=False, verbose_name='TopicID')),
                ('Topic', models.CharField(max_length=200, null=True, verbose_name='Topic')),
                ('DateAdded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateAdded')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.FloatField(null=True)),
                ('Resale', models.FloatField(null=True)),
                ('TradePrice', models.FloatField(null=True)),
                ('Qty', models.IntegerField(null=True)),
                ('TradeAllowed', models.IntegerField(null=True)),
                ('PercentTrade', models.FloatField(null=True)),
                ('CoverPrice', models.FloatField(null=True)),
                ('Discount', models.IntegerField(null=True)),
                ('NonTradex', models.FloatField(null=True, verbose_name='Non-Trade_x')),
                ('LastUpdate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('NoTradeAllowed', models.IntegerField(null=True)),
                ('TaxExempt', models.IntegerField(null=True)),
                ('DateOfSale', models.DateField(default=django.utils.timezone.now, null=True)),
                ('Tax', models.FloatField(null=True)),
                ('Cash', models.FloatField(null=True)),
                ('Check', models.FloatField(null=True)),
                ('CheckNum', models.FloatField(null=True)),
                ('GiftCert', models.FloatField(null=True)),
                ('Description', models.CharField(max_length=255, null=True)),
                ('TaxRate', models.FloatField(null=True)),
                ('SalesPerson', models.CharField(max_length=255, null=True)),
                ('Type', models.CharField(max_length=255, null=True)),
                ('TradeCost', models.FloatField(null=True)),
                ('InOut', models.FloatField(null=True, verbose_name='In/Out')),
                ('NonTradeY', models.FloatField(null=True, verbose_name='Non-Trade_Y')),
                ('Listed', models.FloatField(null=True)),
                ('Sold', models.FloatField(null=True)),
                ('Paid', models.FloatField(null=True)),
                ('BookID', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='home.books')),
                ('ConditionID', models.ForeignKey(db_column='ConditionID', on_delete=django.db.models.deletion.CASCADE, to='home.conditions')),
                ('CoverID', models.ForeignKey(db_column='CoverID', on_delete=django.db.models.deletion.CASCADE, to='home.covertype')),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='home.customers')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='PublisherID',
            field=models.ForeignKey(db_column='PublisherID', on_delete=django.db.models.deletion.CASCADE, to='home.publishers'),
        ),
        migrations.AddField(
            model_name='books',
            name='SeriesID',
            field=models.ForeignKey(db_column='SeriesID', on_delete=django.db.models.deletion.CASCADE, to='home.series'),
        ),
        migrations.AddField(
            model_name='books',
            name='TopicID',
            field=models.ForeignKey(db_column='TopicID', on_delete=django.db.models.deletion.CASCADE, to='home.topics'),
        ),
        migrations.AddField(
            model_name='authors',
            name='PrimaryTopic',
            field=models.ForeignKey(db_column='PrimaryTopic', on_delete=django.db.models.deletion.CASCADE, to='home.topics'),
        ),
    ]
