# Generated by Django 3.2 on 2021-04-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210419_2152'),
    ]

    operations = [
    ]
