# Generated by Django 3.2 on 2021-04-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Labels',
            field=models.IntegerField(null=True, verbose_name='labels'),
        ),
    ]
