# Generated by Django 3.1.7 on 2021-05-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transactions_labels'),
        ('home', '0003_auto_20210420_1527'),
    ]

    operations = [
    ]
