# Generated by Django 3.1.7 on 2021-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20210510_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='TopicID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='TopicID'),
        ),
    ]
