# Generated by Django 3.1.7 on 2021-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210519_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='TopicID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='TopicID'),
        ),
    ]
