# Generated by Django 3.1.7 on 2021-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210519_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='AuthorID',
            field=models.BigAutoField(db_column='AuthorID', primary_key=True, serialize=False, verbose_name='AuthorID'),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookID',
            field=models.BigAutoField(db_column='BookID', primary_key=True, serialize=False, verbose_name='BookID'),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='ConditionID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ConditionID'),
        ),
        migrations.AlterField(
            model_name='covertype',
            name='CoverID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='CoverID'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='CustomerID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='PublisherID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='PublisherID'),
        ),
        migrations.AlterField(
            model_name='series',
            name='SeriesID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='SeriesID'),
        ),
        migrations.AlterField(
            model_name='smallshelfsigns',
            name='SignID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='SignID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
