# Generated by Django 3.1.7 on 2021-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210519_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='PublisherID',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='PublisherID'),
        ),
    ]
